### PR TITLE
removed reference to swaggerhub

### PR DESCRIPTION
**Pull request by syalam**
removed reference to swaggerhub as the current state of swaggerhub documentation is not up to date. this causes confusion when customers read the user guide and expect certain endpoints etc.

### CODE REVIEW

**Comment by aprostrollo** [comment]
It also looks like the changes also include changes from Python 3 to Python 2.  That needs to be corrected.  In addition, the document header information needs to be updated:

- Document Revision:  2.1
- API Version: 1.2.0
- Date:  April 3, 2018

In addition, Gerardo had made a change to the document in the blastmotion/blast-org-api repo (as Rev. 2.0) before he left.  Should we be using that as the baseline for these changes?  I checked for differences this afternoon, and the only thing visible was the response samples included.  The sequencing of the fields for some of the responses is different, which I'm assuming matches what's in API Version 1.2.0.  If you run the cells, that should be automatically updated, though, since the document is interactive.

**Comment by syalam** [comment]
Latest push should use Python 3.6 instead of 2.7

**Comment by aprostrollo** [comment]
It looks like most of the 2.7 references are gone.  There is still one left:  "pip 9.0.1 from /anaconda2/lib/python2.7/site-packages (python 2.7)\r\n"

**Comment by syalam** [comment]
I'm not sure if I can fix that, I have both 2.7 (default Mac OS Python env) and Python 3.6. When I ran the notebook, I ran it with my Python 3.6 environment.

Usually this environment specific configuration is .gitignore'd so we don't mix configuration w/ code. From what I understand about Jupyter Notebooks is that it treats all of this as metadata per whatever environment is on your local machine. So it doesn't affect the execution of the Notebook. The notebook assumes your local configuration and then it is recorded as metadata, which is why it appears in Git like this.

It shouldn't be an issue -- if you pull it and run it on your local env you should be able to run it, and you'll also notice the metadata is updated to your local configuration (ie. whatever filepath your Python version is stored etc. it will be different from mine).

**Comment by aprostrollo** [comment]
That makes sense.  I just looked at where it's appearing in the Notebook, and that should be fine.  As a matter of fact, if the user sees 2.x appear instead of 3.x in that particular spot, it should be a red flag that they aren't running the recommended version.

**Pull request merged**
